---
# Configure system 

  - name: Configure dotfiles
    tags: config
    block:
      - name: Backup dotfiles
        include_tasks: "backup.yml"

  - name: Stow dotfiles
    tags: config
    environment:
      STOW_DIR: "{{ ansible_env.HOME }}/.dotfiles/configs"
    ansible.builtin.shell: |
      stow -t {{ ansible_env.HOME }} nvim tmux zsh starship alacritty
    changed_when: false
    become: true
    become_user: "{{ ansible_user_id }}"
...
