---
# Common terminal packages

- name: Common packages
  tags: common
  block:
    - name: Install MacOS packages 
      include_tasks: "macos.yml"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Linux packages 
      include_tasks: "macos.yml"
      when: ansible_facts['os_family'] != "Darwin"
...
