- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_check
  ignore_errors: yes
  changed_when: false

- name: Install Rust
  become: false
  when: cargo_check.rc != 0
  shell: >
    curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo" 