---
- name: Install OpenJDK
  become: true
  block:
    - name: Install OpenJDK package (arch)
      ansible.builtin.package:
        name: jdk-openjdk
        state: present
      when: ansible_facts['os_family'] == "Archlinux"
    
    - name: Install OpenJDK package 
      ansible.builtin.package:
        name: java-latest-openjdk.x86_64
        state: present
      when: ansible_facts['os_family'] in ['RedHat', 'Fedora'] 