require("config.options")
require("config.keymaps")
require("config.lazy")

-- require("user.impatient")
-- require("user.colorscheme")
-- require("user.options")
-- require("user.keymaps")
-- require("user.plugins")
-- require("user.cmp")
-- require("user.lsp")
-- require("user.telescope")
-- require("user.treesitter")
-- require("user.autopairs")
-- require("user.comment")
-- require("user.gitsigns")
-- require("user.nvim-tree")
-- require("user.bufferline")
-- require("user.lualine")
-- require("user.toggleterm")
-- require("user.indent-blankline")
-- require("user.whichkey")
-- require("user.alpha")
-- require("user.project")
