- name: Install nvim
  become: true
  ansible.builtin.package:
    name: neovim 
    state: latest

- name: Ensure .config/nvim directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: "0755"

- name: Link nvim config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/nvim/files/nvim/"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: true