---
# Dev specific packages

- name: dev tasks
  tags: dev
  block:
    - name: Install MacOS dev packages 
      include_tasks: "macos.yml"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Linux dev packages 
      include_tasks: "linux.yml"
      when: ansible_facts['os_family'] != "Darwin"
...
