---
- name: Install tmux 
  become: true
  ansible.builtin.package:
    name: tmux
    state: latest

- name: Create symlink for .tmux.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/tmux/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
    force: true