---
# Configure system 

  - name: Configure dotfiles
    tags:
      - wsl
    block:
      - name: Change Shell to zsh
        become: true
        user:
          name: "{{ user }}"
          shell: /bin/zsh
          state: present

      - debug:
          msg: "{{ user }}"
          
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: "{{ ansible_env.HOME }}/.rc.old" 
          state: directory
          mode: '0755'

  - name: Stow dotfiles
    tags: config
    environment:
      STOW_DIR: "{{ ansible_env.HOME }}/.dotfiles/configs"
    ansible.builtin.shell: |
      stow -t {{ ansible_env.HOME }} nvim tmux zsh starship
    changed_when: false
    become: false
...
